config/routes.rb
Rails.application.routes.draw do
  #resources :gossip , only: [:new,:create] 
	root 'gossip#index'

  resources :gossip
  resources :cities, only: [:show ]
  resources :comments
  resources :user
  resources :sessions, only: [:new, :create, :destroy]
	#get 'cities/:id', to: 'cities#show', as: 'city'

  #get 'user/:id', to: 'user#show', as: 'user'
  get 'team', to: 'front#team'
  get 'contact', to: 'front#contact'
  get 'welcome/:first_name', to: 'front#welcome'

  # For details on the DSL available within this file, 
  # see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users

	validates :name,
			presence: true,
            uniqueness: true,
            length: {in: 3..30}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :tags
	has_many :comments
	has_many :tags, through: :gossip_tags
	
	validates :title, 
	presence: true,
	length: {in: 3..14}
	validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
	belongs_to :gossip
  	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :gossip
	belongs_to :comment
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  	belongs_to :recipient, class_name: "User"

  	validates :content,
    presence: true,
    length: {in: 3..300}
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips
	has_many :gossips, through: :gossip_tags

	validates :title, length: {in: 3..14}
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password

	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

   validates :first_name,
    presence: true,
    length: {in: 3..30}
  validates :last_name,
    presence: true,
    length: {in: 3..30}
  validates :email,
    presence: true,
    uniqueness: true,
    length: {in: 5..100},
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Le email n'est pas valide" }

    def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

	private
	
	def authenticate_user
    unless current_user
      flash[:danger] = "Please log in."
      redirect_to new_session_path
    end
  end

end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])
    @gossips = []

    City.all.each do |city|
      city.users.where(city_id: params[:id]).each do |user|
        user.gossips.each do |gossip|
          @gossips << gossip
        end
      end
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :destroy]
  	# View list of comments (order most recents first)
    def index
      @comments = Comment.all.order("created_at DESC")
    end

    # View a comment
    def show
      @comment = Comment.find(params[:id])
    end

    # Display a view to create a comment
    def new
      @comment = Comment.new
    end

    # Create a new comment
    def create
      @comment = Comment.new(content: params[:content],
                           user: current_user)

      if @comment.save
        flash[:success] = "Le commentaire a été créé avec succès."
        redirect_to gossips_path
      else
        render 'gossips_path'
      end
    end

    # Display a view with a form to edit an existing comment
    def edit
      @comment = Comment.find(params[:id])
    end

    # Edit an existing comment
    def update
      @comment = Comment.find_by(title: params[:title])

      if @comment.update(content: params[:content], user: current_user)
        flash[:success] = "Le commentaire a été mis à jour avec succès."
        redirect_to gossips_path
      else
        render 'edit'
      end
    end

    # Delete a comment
    def destroy
      Gossip.find(params[:id]).delete
      redirect_to gossips_path
    end
  end
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def team
  end

  def contact
  end

  def welcome
  	puts "$"*60
  	#@first_name = "Miguel"
  	@first_name = params[:first_name]
  	puts "l'utilisateur a tapé #{@first_name}"
  	puts "$"*60
  end

end

#def gossips
#     gossips = Gossip.all
#    @id = 1
#    @author = "Titre du potin"
#   @title = "Titre du potin"
#   @content = "content"
# end

  # View a gossip
#  def gossip
#     gossip = Gossip.find(params['id'])
#   @author = "Author du potin"
#   @title = "Titre du potin"
#   @content = "content"
#end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :destroy]
    def new
    	 @gossip = Gossip.new
    end

    def create
  	  	puts params
  	    @gossip = Gossip.new(title: params[:title],
                           content: params[:content],)
        @gossip.user = current_user
      	# @gossip = Gossip.new(params[:post])
  	    if @gossip.save # essaie de sauvegarder en base @gossip
          flash[:success] = "Potin bien créé !" #Message flash
  	    	redirect_to gossip_index_path # si ça marche, il redirige vers la page d'index du site
  	  else
  	    	render 'new'# sinon, il render la view new (qui est celle sur laquelle on est déjà)
  	  end
    end

     # View list of gossips (order most recents first)
    def index
      @gossips = Gossip.all.order("created_at DESC")
    end

    # View a gossip
    def show
      @gossip = Gossip.find(params[:id])
    end

    # Edit an existing gossip
    def edit
      @gossip = Gossip.find(params[:id])
    end
      def update
      	@gossip = Gossip.find(params[:id])
      if @gossip.update(title: params[:title], content: params[:content], user: User.find(params[:user]))
    	flash[:success] = "Le potin a été mis à jour avec succès."
        redirect_to gossip_index_path
      else
        render 'edit'
      end

    end

    # Delete a gossip
    def destroy
      Gossip.find(params[:id]).delete
      redirect_to gossip_index_path
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :authenticate_user, only: [:index]
  #def index
  #	redirect_to show_user_path
  #end

  def new
  	@user = User.new
  end

  def create
	 #On cherche s'il existe un utilisateur dans la BD
	 @user = User.find_by(email: params[:email])

	 #on vérifie si l'utilisateur existe bien ET si on arrive 
	 #à l'authentifier (méthode bcrypt) avec le mot de passe 
	  if @user && @user.authenticate(params[:password])
	    session[:user_id] = @user.id
	    redirect_to user_path(@user.id)
	    # redirige où tu veux, avec un flash ou pas
	  else
	    flash.now[:danger] = 'Invalid email/password combination'
	    render :new
	  end
  end

  def destroy
	session.delete(:user_id)
    redirect_to :root
  end

  private

  def authenticate_user
	    unless current_user
	      flash[:danger] = "Please log in."
	      redirect_to new_session_path
	    end
	end

end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
 @gossips = Gossip.all.order("created_at DESC")
  end

  def new
  	@user = User.new
  end

  def create
	user = User.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        description: params[:description],
        email: params[:email],
        age: params[:age],
        city: City.find(params[:city]),
        password: params[:password], #password bcrypt
        password_confirmation: params[:password_confirmation]
    )
     if user.save && password == password_confirmation
      flash[:success] = "Votre compte a bien été créé !"
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def current_user
    User.find_by(id: session[:user_id])
	end

	def log_in(user)
    session[:user_id] = user.id
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/cities/show.html.erb
<h1>Ville</h1>
<p>Bienvenu sur le site de <%= @city.name %></p>

<h2 class="h1 text-center mb-4 text-uppercase">Liste des potins à <%=@city.name %></h2>

<!-- Main content -->
<div class="row">
<% @gossips.each do |gossip| %>
    <div class="col-4 mb-3">
      <div class="card">
        <img class="card-img-top" alt="Card image cap" src="https://actu.meilleurmobile.com/wp-content/uploads/2015/06/gossip-application.jpg">
        <div class="card-body">
          <h5 class="card-title"><%=gossip.title %></h5>
          <p class="card-text"><%= truncate gossip.content, length: 30 %></p>
          <p class="card-text">
            <small class="text-muted">
              posté par <a href="<%= user_path(gossip.user.id) %>"><%=gossip.user.first_name %></a>
              le <%=gossip.created_at.strftime("%d/%m/%Y %H:%I") %>
              à <a href="<%=city_path(gossip.user.city.id)%>"><%=@city.name %></a>
            </small>
          </p>
          <div class="row justify-content-center">
            <div class="col">
              <%= form_tag gossip_path(gossip.id), method: "get" do %>
                <%= submit_tag "Voir le potin", {class: 'btn btn-info btn-block'} %>
              <% end %>
            </div>
            <div class="col">
              <%= form_tag gossip_path(gossip.id), method: "delete", style: "display: inline" do %>
                <%= submit_tag "Supprimer", {class: 'btn btn-danger btn-block'} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
 </div>
<%#=render "layouts/gossips_list" %>

app/views/gossip/edit.html.erb
<!-- Content title -->
<h2 class="display-4 text-center my-3"></h2>

<!-- Flash message -->
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row justify-content-center">
  <div class="col-6">
    <%= form_tag url_for(action: 'update'), method: "patch" do %>
      <div class="form-group">
        <%= label_tag 'Titre :' %>
        <%= text_field_tag 'title', @gossip.title, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= label_tag 'Contenu :' %>
        <%= text_area_tag 'content', @gossip.content, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= label_tag 'Auteur :' %>
        <%= select_tag "user", options_from_collection_for_select(User.all, :id, :full_name), {class: 'form-control' } %>
      </div>
      <div class="row justify-content-center">
          <%= submit_tag "Editer le potin", {class: 'btn btn-primary'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/gossip/index.html.erb
<h1 class="text-center">Bienvenu(e) </h1>
<% if flash[:success] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:success] %>
  </div>
<% end %>

<!-- Main content -->
<%= render "layouts/gossip_list" %>

app/views/gossip/new.html.erb
<h1>Gossip#new</h1>
<p>Find me in app/views/gossip/new.html.erb</p>
<h2 class="text-center my-5">Créer un nouveau potin</h2>

<!-- Flash message -->
<% if @gossip.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer le potin pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @gossip.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

div class="row justify-content-center">
  <div class="col-6">
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <div class="form-group">
        <%= label_tag 'Titre :' %>
        <%= text_field_tag 'title', @gossip.title, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= label_tag 'Contenu :' %>
        <%= text_area_tag 'content', @gossip.content, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= label_tag 'Auteur :' %>
        <%= select_tag "user", options_from_collection_for_select(User.all, :id, :full_name), {class: 'form-control' } %>
      </div>
      <div class="row justify-content-center">
          <%= submit_tag "Créer le potin", {class: 'btn btn-primary'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/gossip/show.html.erb
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card">
      <img class="card-img-top" alt="Card image cap" src="https://actu.meilleurmobile.com/wp-content/uploads/2015/06/gossip-application.jpg">
      <div class="card-body">
        <h5 class="card-title"><%=@gossip.title %></h5>
        <p class="card-text"><%= @gossip.content %></p>
        <p class="card-text">
        <p class="card-text">
          <small class="text-muted">
            posté par <a href="<%= user_path(@gossip.user.id) %>"><%=@gossip.user.first_name %></a>
            le <%=@gossip.created_at.strftime("%d/%m/%Y à %H:%I") %>
            à <%=@gossip.user.city.name %>
          </small>
        </p>
        <div class="row justify-content-center">
           <div class="row justify-content-center">
            <div class="col">
              <a class='btn btn-info btn-block' href="<%= edit_gossip_path %>">Editer</a>
            </div>
            <div class="col">
              <%= form_tag gossip_path(@gossip.id), method: "delete" do %>
                <%= submit_tag "Supprimer", {class: 'btn btn-danger btn-block'} %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
 <!-- List Comments -->
  <div class="col-7">
    <h2 class="display-4 text-center my-3">Commentaires</h2>
    <%if @gossip.comments.empty? %>
      <p>Aucun commentaire</p>
    <% else %>
      <section class="comment-list" style="margin-top: -3em">
        <% i = 0 %>
        <% @comments.each do |comment| %>
          <% if i % 2 === 0 %>
            <!-- Right Comment -->
            <article class="row">
              <div class="col-md-2 col-sm-2 hidden-xs">
                <figure class="thumbnail">
                  <img class="img-responsive" src="<%= image_path 'bento_cowboy.png' %>"  alt=""/>
                  <figcaption class="text-center"> <%=comment.user.full_name %></figcaption>
                </figure>
              </div>
              <div class="col-md-10 col-sm-10">
                <div class="panel panel-default arrow left">
                  <div class="panel-body">
                    <header class="text-left">
                      <div class="comment-user"><i class="fa fa-user"></i> <%=comment.user.full_name %></div>
                      <time class="comment-date" datetime="16-12-2014 01:05"><i class="fa fa-clock-o"></i> <%=comment.user.created_at.strftime("%d %b %Y à %H:%I") %></time>
                    </header>
                    <div class="comment-post">
                      <p><%=comment.content %></p>
                    </div>
                    <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p>
                  </div>
                </div>
              </div>
            </article>
          <% else %>
            <!-- Left Comment -->
            <article class="row">
              <div class="col-md-10 col-sm-10">
                <div class="panel panel-default arrow right">
                  <div class="panel-body">
                    <header class="text-right">
                      <div class="comment-user"><%=comment.user.full_name %> <i class="fa fa-user"></i></div>
                      <time class="comment-date" datetime="16-12-2014 01:05"><%=comment.user.created_at.strftime("%d %b %Y à %H:%I") %> <i class="fa fa-clock-o"></i></time>
                    </header>
                    <div class="comment-post">
                      <p><%=comment.content %></p>
                    </div>
                    <p class="text-right"><a href="#" class="btn btn-default btn-sm"><i class="fa fa-reply"></i> reply</a></p>
                  </div>
                </div>
              </div>
              <div class="col-md-2 col-sm-2 hidden-xs">
                <figure class="thumbnail">
                  <img class="img-responsive" src="<%= image_path 'bento_pic.png' %>" />
                  <figcaption class="text-center"><%=comment.user.full_name %></figcaption>
                </figure>
              </div>
            </article>
          <% end %>
          <% i += 1 %>
        <% end %>
      </section>
    <% end %>

    <!-- Add a comment -->
    <%comment = Comment.new%>
    <div class="row justify-content-center">
      <div class="col-12">
        <%= form_tag url_for(action: 'create'), method: "post" do %>
          <div class="form-group">
            <%= label_tag 'Ajouter un commentaire :' %>
            <%= text_area_tag 'content', comment.content, {class: 'form-control', rows: 5, placeholder: "Saisissez votre commentaire..."} %>
          </div>
          <div class="row justify-content-center">
            <%= submit_tag "Valider", {class: 'btn btn-primary'} %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/user/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/user/new.html.erb
<h1>User#new</h1>
<p>Find me in app/views/user/new.html.erb</p>

<!-- Flash message -->
<% if @user.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <p>Nous n'avons pas réussi à créer l'utilisateur pour la (ou les) raison(s) suivante(s) :</p>
    <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="row justify-content-center"  style="margin-bottom: 100px;">
  <div class="col-6">
    <%= form_tag url_for(action: 'create'), method: "post" do %>
      <div class="form-group">
        <%= label_tag 'Prénom* :' %>
        <%= text_field_tag 'first_name', @user.first_name, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Nom* :' %>
        <%= text_field_tag 'last_name', @user.last_name, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Description* :' %>
        <%= text_area_tag 'description', @user.description, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Email* :' %>
        <%= email_field_tag 'email', @user.email, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Mot de passe* :' %>
        <%= text_field_tag 'password', @user.password, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Saisir à nouveau le mot de passe* :' %>
        <%= text_field_tag 'password_confirmation', @user.password, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Age* :' %>
        <%= number_field_tag 'age', @user.age, {class: 'form-control'} %>
      </div>

      <div class="form-group">
        <%= label_tag 'Ville :' %>
        <%= select_tag "city", options_from_collection_for_select(City.all, :id, :name), {class: 'form-control' } %>
      </div>

      <div class="row justify-content-center">
        <%= submit_tag "Valider mon inscription", {class: 'btn btn-primary'} %>
      </div>
    <% end %>
  </div>
</div>

app/views/user/show.html.erb
<div class="container">
  <h1 class="display-4 text-center">The Gossip Project</h1>

  <p>N° Utilisateur : <%= @user.id %></p>
  <p>Prénom : <%= @user.first_name %></p>
  <p>Nom : <%= @user.last_name %></p>
  <p>description : <%= @user.description %></p>
  <p>email : <%= @user.email %></p>
  <p>âge : <%= @user.age %></p>
  <p>ville : <a href="<%=city_path(@user.city.id) %>"><%=@user.city.name %></a></p>
</div>