config/routes.rb
Rails.application.routes.draw do
  #resources :gossip , only: [:new,:create] 
	root 'gossip#index'

  resources :gossip
  resources :cities, only: [:show ]
  resources :comments
  resources :user
  resources :sessions, only: [:new, :create, :destroy]
	#get 'cities/:id', to: 'cities#show', as: 'city'

  #get 'user/:id', to: 'user#show', as: 'user'
  get 'team', to: 'front#team'
  get 'contact', to: 'front#contact'
  get 'welcome/:first_name', to: 'front#welcome'

  # For details on the DSL available within this file, 
  # see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
	has_many :users

	validates :name,
			presence: true,
            uniqueness: true,
            length: {in: 3..30}
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :gossip
	has_many :likes
end

app/models/gossip.rb
class Gossip < ApplicationRecord
	belongs_to :user
	has_many :tags
	has_many :comments
	has_many :tags, through: :gossip_tags
	
	validates :title, 
	presence: true,
	length: {in: 3..14}
	validates :content, presence: true
end

app/models/gossip_tag.rb
class GossipTag < ApplicationRecord
	belongs_to :gossip
  	belongs_to :tag
end

app/models/like.rb
class Like < ApplicationRecord
	belongs_to :gossip
	belongs_to :comment
end

app/models/private_message.rb
class PrivateMessage < ApplicationRecord
	belongs_to :sender, class_name: "User"
  	belongs_to :recipient, class_name: "User"

  	validates :content,
    presence: true,
    length: {in: 3..300}
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :gossips
	has_many :gossips, through: :gossip_tags

	validates :title, length: {in: 3..14}
end

app/models/user.rb
class User < ApplicationRecord
has_secure_password

	belongs_to :city
	has_many :gossips
	has_many :sent_messages, foreign_key: 'sender_id', class_name: "PrivateMessage"
	has_many :received_messages, foreign_key: 'recipient_id', class_name: "PrivateMessage"

   validates :first_name,
    presence: true,
    length: {in: 3..30}
  validates :last_name,
    presence: true,
    length: {in: 3..30}
  validates :email,
    presence: true,
    uniqueness: true,
    length: {in: 5..100},
    format: { with: /\A[^@\s]+@([^@\s]+\.)+[^@\s]+\z/, message: "Le email n'est pas valide" }

    def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController
  def show
  	@city = City.find(params[:id])
    @gossips = []

    City.all.each do |city|
      city.users.where(city_id: params[:id]).each do |user|
        user.gossips.each do |gossip|
          @gossips << gossip
        end
      end
    end
  end

end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def team
  end

  def contact
  end

  def welcome
  	puts "$"*60
  	#@first_name = "Miguel"
  	@first_name = params[:first_name]
  	puts "l'utilisateur a tapé #{@first_name}"
  	puts "$"*60
  end

end

#def gossips
#     gossips = Gossip.all
#    @id = 1
#    @author = "Titre du potin"
#   @title = "Titre du potin"
#   @content = "content"
# end

  # View a gossip
#  def gossip
#     gossip = Gossip.find(params['id'])
#   @author = "Author du potin"
#   @title = "Titre du potin"
#   @content = "content"
#end

app/controllers/gossip_controller.rb
class GossipController < ApplicationController
  before_action :authenticate_user, only: [:new, :create, :destroy]
    def new
    	 @gossip = Gossip.new
    end

    def create
  	  	puts params
  	    @gossip = Gossip.new(title: params[:title],
                           content: params[:content],)
        @gossip.user = current_user
      	# @gossip = Gossip.new(params[:post])
  	    if @gossip.save # essaie de sauvegarder en base @gossip
          flash[:success] = "Potin bien créé !" #Message flash
  	    	redirect_to gossip_index_path # si ça marche, il redirige vers la page d'index du site
  	  else
  	    	render 'new'# sinon, il render la view new (qui est celle sur laquelle on est déjà)
  	  end
    end

     # View list of gossips (order most recents first)
    def index
      @gossips = Gossip.all.order("created_at DESC")
    end

    # View a gossip
    def show
      @gossip = Gossip.find(params[:id])
    end

    # Edit an existing gossip
    def edit
      @gossip = Gossip.find(params[:id])
    end
      def update
      	@gossip = Gossip.find(params[:id])
      if @gossip.update(title: params[:title], content: params[:content], user: User.find(params[:user]))
    	flash[:success] = "Le potin a été mis à jour avec succès."
        redirect_to gossip_index_path
      else
        render 'edit'
      end

    end

    # Delete a gossip
    def destroy
      Gossip.find(params[:id]).delete
      redirect_to gossip_index_path
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
 @gossips = Gossip.all.order("created_at DESC")
  end

  def new
  	@user = User.new
  end

  def create
	user = User.new(
        first_name: params[:first_name],
        last_name: params[:last_name],
        description: params[:description],
        email: params[:email],
        age: params[:age],
        city: City.find(params[:city]),
        password: params[:password], #password bcrypt
        password_confirmation: params[:password_confirmation]
    )
     if user.save && password == password_confirmation
      flash[:success] = "Votre compte a bien été créé !"
      redirect_to root_path
    else
      redirect_to new_user_path
    end
  end

  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/gossip_helper.rb
module GossipHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	
	def current_user
    User.find_by(id: session[:user_id])
	end

	def log_in(user)
    session[:user_id] = user.id
	end

end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_gossip_list.html.erb
<div class="row">
<div class="row">
  <% @gossips.each do |gossip| %>
    <div class="col-4 mb-3">
      <div class="card">
        <div class="card-header">
          <%= form_tag gossip_path(gossip.id), method: "delete", style: "display: inline" do %>
            <button class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
        <% end %>
        </div>
        <img class="card-img-top" alt="Card image cap" src="https://actu.meilleurmobile.com/wp-content/uploads/2015/06/gossip-application.jpg">
        <div class="card-body text-center">
          <h5 class="card-title"><%=gossip.title %></h5>
          <p class="card-text"><%= truncate gossip.content, length: 30 %></p>
          <a href="<%= gossip_path(gossip.id) %>" class="btn btn-info btn-block btn-sm">Voir le potin</a>
        </div>
        <div class="card-footer text-center">
          <small class="text-muted">
            <i class="fas fa-user"></i> Par <a href="<%= user_path(gossip.user.id) %>"><%=gossip.user.first_name %></a>
            <i class="far fa-calendar-alt"> le </i> <%=gossip.created_at.strftime("%d/%m/%Y") %>
            <i class="far fa-building"></i> à <a href="<%= city_path(gossip.user.city.id) %>"><%=gossip.user.city.name %></a>
            <br />
            <span class="text-muted"><%= gossip.comments.count %> commentaires</span>
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TheGossipProject2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <nav class="navbar navbar-light" style="background-color: #7C53B8;">
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="/">The Gossip Project</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Navbar -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            <a class="nav-link" href="<%=team_path%>">Equipe
              <span class="sr-only"></span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=contact_path %>">Contact</a>
          </li>
          <% if !current_user %>
          <!-- Options pour se conecter -->
          <li class="nav-item">
          <a class="btn btn-primary btn-sm" href="<%=new_session_path %>"><i class="fas fa-sign-in-alt"></i> Se connecter</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="<%=new_user_path %>">Créer une compte</a>
          </li>
          </ul>
        </div>
      </nav>
    </nav>
  </header>
          <%else%>
          <!-- Si on a une connexion-->
          
          <li class="nav-item">
            <a class="nav-link" href="<%=city_path(current_user.city.id) %>"><%=current_user.city.name %></a>
          </li>
          <li>
          <a class="btn btn-outline-success my-2 my-sm-0 text-success mx-3" href="<%=new_gossip_path %>">Nouveau Gossip</a>
        </li>
          <li class="nav-item">
            <%= link_to "Se déconnecter", session_path(session.id), method: :delete %>
          </li>
        </ul>
        </div>
    </nav>
  </nav>
</header>
            <p class="lead text-center">Bienvenue à nouveau <%= User.find_by(id: session[:user_id]).first_name %> !</p>
          <% end %>
    <%= yield %>
  </body>
</html>